### ISSUE TITLE
Failed to get biome id on 1.16.2 in prod

### ISSUE THREAD

**Issue by lhns** [LolHens/dynmap-fabric#12]
```
java.lang.NullPointerException: null
	at org.dynmap.fabric_1_16_1.DynmapPlugin.loadExtraBiomes(DynmapPlugin.java:405) ~[dynmap-fabric-0.0.1-SNAPSHOT+1.16.2.jar:?]
	at org.dynmap.fabric_1_16_1.DynmapPlugin.onEnable(DynmapPlugin.java:447) ~[dynmap-fabric-0.0.1-SNAPSHOT+1.16.2.jar:?]
	at org.dynmap.fabric_1_16_1.DynmapPlugin.serverStart(DynmapPlugin.java:303) ~[dynmap-fabric-0.0.1-SNAPSHOT+1.16.2.jar:?]
	at org.dynmap.fabric_1_16_1.DynmapPlugin$$Lambda$2282/1846187858.onServerStarting(Unknown Source) ~[?:?]
	at net.minecraft.server.MinecraftServer.handler$zzh000$beforeSetupServer(MinecraftServer.java:1725) ~[intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:642) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$4267/1216520909.run(Unknown Source) [intermediary-fabric-loader-0.9.1+build.205-1.16.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by lhns** [comment]
fixed by e7ea0257c693e3b617471582c94f80b1d2a777b9
