### ISSUE TITLE
Error on startup 1.16 0.2.14

### ISSUE THREAD

**Issue by LarveyOfficial** [LolHens/dynmap-fabric#29]
```openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)
:/home/container$ java -Xms128M -Xmx12228M -jar fabric-server-launch.jar
[04:13:25] [main/INFO]: Loading for game Minecraft 1.16.1
[04:13:25] [main/INFO]: [FabricLoader] Loading 45 mods: fabric-screen-handler-api-v1@1.1.0+97324d1102, minecraft@1.16.1, fabric-renderer-api-v1@0.2.13+eae12eb802, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, fabric-keybindings-v0@0.2.0+3fa9f7c502, dynmap@0.2.14+1.16.1, fabric-command-api-v1@1.0.8+5ce5339802, fabricloader@0.9.1+build.205, phosphor@0.6.0+build.7, fabric-tool-attribute-api-v1@1.2.1+91fca5cd02, fabric-renderer-indigo@0.3.4+34d6c87102, lithium@0.5.1, fabric-containers-v0@0.1.8+045df74f02, fabric-object-builder-api-v1@1.5.7+2242e77202, fabric-dimensions-v1@1.0.0+a71b305302, fabric-biomes-v1@0.2.7+059ea86602, fabric-item-api-v1@1.0.0+16acbe5b02, fabric-events-interaction-v0@0.3.3+7066030f02, fabric-crash-report-info-v1@0.1.2+b7f9825d02, fabric-game-rule-api-v1@1.0.0+fe81e12502, fabric-api-base@0.1.3+12a8474c02, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, fabric-key-binding-api-v1@1.0.1+f404f3be02, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, fabric-resource-loader-v0@0.2.6+f41e209802, fabric-textures-v0@1.0.4+eae12eb802, fabric-content-registries-v0@0.1.9+059ea86602, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, fabric-rendering-fluids-v1@0.1.8+b7084faa02, fabric-registry-sync-v0@0.3.8+7dba2d6c02, fabric-commands-v0@0.2.0+52d3083602, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, fabric-lifecycle-events-v1@1.2.0+e83e061c02, sodium@0.1.0, fabric-mining-levels-v0@0.1.2+b764ce9902, fabric-renderer-registries-v1@2.1.0+be551d3c02, fabric-loot-tables-v1@1.0.0+386eb69e02, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, fabric@0.17.0+build.386-1.16.1, fabric-particles-v1@0.2.1+0a6f2a7002, fabric-item-groups-v0@0.2.0+438f963602, fabric-models-v0@0.1.0+dfdb52d602, fabric-networking-v0@0.1.10+e00ecb5f02, fabric-object-builders-v0@0.6.1+a2d21ddd02
[04:13:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/home/container/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[04:13:28] [main/INFO]: Loaded configuration file for Lithium: 54 options available, 0 override(s) found
[04:13:28] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v0.mixins.json:MixinEntityTracker and should be specified in value
[04:13:28] [main/WARN]: Error loading class: net/minecraft/world/biome/BiomeEffects (java.lang.ClassNotFoundException: net/minecraft/world/biome/BiomeEffects)
[04:13:28] [main/WARN]: @Mixin target net.minecraft.world.biome.BiomeEffects was not found dynmap.mixins.json:BiomeEffectsAccessor
[04:13:28] [main/WARN]: Error loading class: net/minecraft/server/PlayerManager (java.lang.ClassNotFoundException: net/minecraft/server/PlayerManager)
[04:13:28] [main/WARN]: @Mixin target net.minecraft.server.PlayerManager was not found dynmap.mixins.json:PlayerManagerMixin
[04:13:28] [main/WARN]: Error loading class: net/minecraft/server/network/ServerPlayerEntity (java.lang.ClassNotFoundException: net/minecraft/server/network/ServerPlayerEntity)
[04:13:28] [main/WARN]: @Mixin target net.minecraft.server.network.ServerPlayerEntity was not found dynmap.mixins.json:ServerPlayerEntityMixin
[04:13:28] [main/WARN]: Error loading class: net/minecraft/server/network/ServerPlayNetworkHandler (java.lang.ClassNotFoundException: net/minecraft/server/network/ServerPlayNetworkHandler)
[04:13:28] [main/WARN]: @Mixin target net.minecraft.server.network.ServerPlayNetworkHandler was not found dynmap.mixins.json:ServerPlayNetworkHandlerMixin
[04:13:28] [main/WARN]: Error loading class: net/minecraft/server/world/ThreadedAnvilChunkStorage (java.lang.ClassNotFoundException: net/minecraft/server/world/ThreadedAnvilChunkStorage)
[04:13:28] [main/WARN]: @Mixin target net.minecraft.server.world.ThreadedAnvilChunkStorage was not found dynmap.mixins.json:ThreadedAnvilChunkStorageAccessor
[04:13:28] [main/WARN]: Error loading class: net/minecraft/server/world/ThreadedAnvilChunkStorage (java.lang.ClassNotFoundException: net/minecraft/server/world/ThreadedAnvilChunkStorage)
[04:13:28] [main/WARN]: @Mixin target net.minecraft.server.world.ThreadedAnvilChunkStorage was not found dynmap.mixins.json:ThreadedAnvilChunkStorageMixin
[04:13:28] [main/WARN]: Error loading class: net/minecraft/world/chunk/WorldChunk (java.lang.ClassNotFoundException: net/minecraft/world/chunk/WorldChunk)
[04:13:28] [main/WARN]: @Mixin target net.minecraft.world.chunk.WorldChunk was not found dynmap.mixins.json:WorldChunkMixin
[04:13:32] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[04:13:32] [main/FATAL]: Mixin apply failed dynmap.mixins.json:MinecraftServerMixin -> net.minecraft.server.MinecraftServer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on loadWorld could not find any targets matching 'loadWorld' in net.minecraft.server.MinecraftServer. No refMap loaded. [PREINJECT Applicator Phase -> dynmap.mixins.json:MinecraftServerMixin -> Prepare Injections -> -> handler$zeh000$loadWorld(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on loadWorld could not find any targets matching 'loadWorld' in net.minecraft.server.MinecraftServer. No refMap loaded. [PREINJECT Applicator Phase -> dynmap.mixins.json:MinecraftServerMixin -> Prepare Injections -> -> handler$zeh000$loadWorld(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[fabric-server-launch.jar:?]
at sun.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source) ~[?:?]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_262]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_262]
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) [fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-server-launch.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_262]
at net.minecraft.server.Main.main(Main.java:115) [intermediary-server.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
[04:13:32] [main/INFO]: [STDERR]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [dynmap.mixins.json:MinecraftServerMixin] from phase [DEFAULT] in config [dynmap.mixins.json] FAILED during APPLY
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
[04:13:32] [main/INFO]: [STDERR]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[04:13:32] [main/INFO]: [STDERR]: at net.minecraft.server.Main.main(Main.java:115)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:13:32] [main/INFO]: [STDERR]: at java.lang.reflect.Method.invoke(Method.java:498)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:13:32] [main/INFO]: [STDERR]: at java.lang.reflect.Method.invoke(Method.java:498)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
[04:13:32] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on loadWorld could not find any targets matching 'loadWorld' in net.minecraft.server.MinecraftServer. No refMap loaded. [PREINJECT Applicator Phase -> dynmap.mixins.json:MinecraftServerMixin -> Prepare Injections -> -> handler$zeh000$loadWorld(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[04:13:32] [main/INFO]: [STDERR]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[04:13:32] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[04:13:32] [main/INFO]: [STDERR]: ... 21 more
Exception in thread "main" [04:13:32] [main/INFO]: [STDERR]: java.lang.RuntimeException: Failed to setup Fabric server environment!
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
[04:13:32] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
[04:13:32] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
[04:13:32] [main/INFO]: [STDERR]: ... 1 more
[04:13:32] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:13:32] [main/INFO]: [STDERR]: at java.lang.reflect.Method.invoke(Method.java:498)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
[04:13:32] [main/INFO]: [STDERR]: ... 2 more
[04:13:32] [main/INFO]: [STDERR]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[04:13:32] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
[04:13:32] [main/INFO]: [STDERR]: ... 7 more
[04:13:32] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:13:32] [main/INFO]: [STDERR]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:13:33] [main/INFO]: [STDERR]: at java.lang.reflect.Method.invoke(Method.java:498)
[04:13:33] [main/INFO]: [STDERR]: at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[04:13:33] [main/INFO]: [STDERR]: ... 9 more
[04:13:33] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[04:13:33] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[04:13:33] [main/INFO]: [STDERR]: at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
[04:13:33] [main/INFO]: [STDERR]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[04:13:33] [main/INFO]: [STDERR]: at net.minecraft.server.Main.main(Main.java:115)
[04:13:33] [main/INFO]: [STDERR]: ... 14 more
[04:13:33] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [dynmap.mixins.json:MinecraftServerMixin] from phase [DEFAULT] in config [dynmap.mixins.json] FAILED during APPLY
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[04:13:33] [main/INFO]: [STDERR]: ... 21 more
[04:13:33] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on loadWorld could not find any targets matching 'loadWorld' in net.minecraft.server.MinecraftServer. No refMap loaded. [PREINJECT Applicator Phase -> dynmap.mixins.json:MinecraftServerMixin -> Prepare Injections -> -> handler$zeh000$loadWorld(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
[04:13:33] [main/INFO]: [STDERR]: at sun.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source)
[04:13:33] [main/INFO]: [STDERR]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[04:13:33] [main/INFO]: [STDERR]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[04:13:33] [main/INFO]: [STDERR]: at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[04:13:33] [main/INFO]: [STDERR]: ... 21 more
```
Crashes on startup

**Comment by lhns** [comment]
I cannot reproduce this one. I used the same mod version, minecraft version and fabric loader version.

**Comment by LarveyOfficial** [comment]
yeah... make sure the entire Jar file is uploaded to a server
