### ISSUE TITLE
crash in prod

### ISSUE THREAD

**Issue by lhns** [LolHens/dynmap-fabric#7]
```
[00:31:47] [main/INFO]: Jumping to new loader, main class: net.fabricmc.loader.launch.knot.KnotClient
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:180)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$51/842741472.accept(Unknown Source)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
[00:31:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 8 more
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.reflect.InvocationTargetException
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 15 more
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableMap.toImmutableMap(Ljava/util/function/Function;Ljava/util/function/Function;)Ljava/util/stream/Collector;
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_2689.method_28484(class_2689.java:61)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_2689$$Lambda$278/43729075.accept(Unknown Source)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_2689.<init>(class_2689.java:60)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_2689$class_2690.method_11668(class_2689.java:155)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_3611.<init>(class_3611.java:29)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_3576.<init>(class_3576.java:15)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_3612.<clinit>(class_3612.java:6)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_2378.method_10248(class_2378.java:167)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_2378$$Lambda$226/993452032.get(Unknown Source)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_2378.method_29110(class_2378.java:220)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_2378$$Lambda$272/887230059.accept(Unknown Source)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_2378.<clinit>(class_2378.java:219)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.class_2966.method_12851(class_2966.java:41)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main.main(Main.java:137)
[00:31:58] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	... 20 more
```

**Comment by lhns** [comment]
fixed by bf5c60dbd2603268c178588c493b2f55900e30bb
